import 'dart:async';
import 'dart:io';

typedef IOWritterFinalize = Future<void> Function();

class IOWritter {
  final IOSink _inner;
  final IOWritterFinalize _finalize;

  IOWritter._(this._inner, this._finalize);

  factory IOWritter.withFinalizer({
    required IOSink sink,
    required IOWritterFinalize finalizer,
  }) {
    return IOWritter._(sink, finalizer);
  }


  /// Adds byte [data] to the target consumer.
  ///
  /// This operation is non-blocking. See [flush] or [done] for how to get any
  /// errors generated by this call.
  ///
  /// The data list should not be modified after it has been passed to `add`
  /// because it is not defined whether the target consumer will receive the
  /// list in the original or modified state.
  ///
  /// Individual values in [data] which are not in the range 0 .. 255 will be
  /// truncated to their low eight bits, as if by [int.toUnsigned], before being
  /// used.
  void add(List<int> data) => _inner.add(data);

  /// Passes the error to the target consumer as an error event.
  ///
  /// This operation is non-blocking. See [flush] or [done] for how to get any
  /// errors generated by this call.
  void addError(Object error, [StackTrace? stackTrace]) =>
      _inner.addError(error, stackTrace);
  
  /// Perform a final flush and close the target consumer.
  ///
  Future<void> finish() async {
    await _inner.flush();
    await _inner.close();
    await _finalize();
  }

  /// Returns a [Future] that completes once all buffered data is accepted by the
  /// underlying [StreamConsumer].
  ///
  /// NOTE: This is not necessarily the same as the data being flushed by the
  /// operating system.
  Future<void> flush() => _inner.flush();

}
