import 'dart:async';
import 'dart:io';

class IOWriter {
  final IOSink _inner;
  final Future<void> guard;

  IOWriter._(this._inner, this.guard);

  factory IOWriter({required IOSink sink, required Future<void> guard}) {
    return IOWriter._(sink, guard);
  }

  /// Adds byte [data] to the target consumer.
  ///
  /// This operation is non-blocking. See [flush] or [done] for how to get any
  /// errors generated by this call.
  ///
  /// The data list should not be modified after it has been passed to `add`
  /// because it is not defined whether the target consumer will receive the
  /// list in the original or modified state.
  ///
  /// Individual values in [data] which are not in the range 0 .. 255 will be
  /// truncated to their low eight bits, as if by [int.toUnsigned], before being
  /// used.
  void add(List<int> data) => _inner.add(data);

  /// Perform a final flush and close the target consumer.
  ///
  Future<void> finish() async {
    try {
      await _inner.flush();
      await _inner.close();
    } on Object {
      // The backend guard is the authoritative outcome for the write process.
    }

    await guard;
  }

  /// Returns a [Future] that completes once all buffered data is accepted by the
  /// underlying [StreamConsumer].
  ///
  /// NOTE: This is not necessarily the same as the data being flushed by the
  /// operating system.
  Future<void> flush() => _inner.flush();
}
