name: Flasher CI

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled

permissions:
  contents: read

jobs:
  verify:
    if: >
      github.event.pull_request.head.repo.full_name == github.repository ||
      contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    uses: ./.github/workflows/verify.yml
